version: 0.0
os: linux
files:
  - source: BuildArtif/deployment.yml
    destination: /tmp
  - source: BuildArtif/service.yml
    destination: /tmp
  - source: BuildArtif/deploy.sh
    destination: /tmp
hooks:
  BeforeInstall:
    - location: /tmp/deploy.sh
      timeout: 300
      runas: ec2-user
