version: 0.0
os: linux
files:
  - source: deploy.sh
    destination: /tmp
  - source: deployment.yml
    destination: /tmp
  - source: service.yml
    destination: /tmp

hooks:
  BeforeInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
