version: 0.0
os: linux
files:
  - source: scripts/deploy.sh
    destination: /tmp
  - source: kubernetes/deployment.yml
    destination: /tmp
  - source: kubernetes/service.yml
    destination: /tmp

hooks:
  BeforeInstall:
    - location: /tmp/deploy.sh
      timeout: 300
      runas: ec2-user
