apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::513869214497:role/eksctl-brain-tasks-cluster-nodegro-NodeInstanceRole-sYXG6pwuDPOy
      username: system:node:{{EC2PrivateDNSName}}

    - groups:
        - system:masters
      rolearn: arn:aws:iam::513869214497:role/codebuild-role-for-brain-app
      username: codebuild
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
