apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app

    spec:
      containers:
      - name: brain-tasks-container
        image: 513869214497.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
        ports:
          - containerPort: 80  

